-- 1) LIST ALL THE EMPLOYEE DETAILS WITH THIER DEPARTMENT NAME !

-- USING JOINS ( FASTER ONE )

SELECT E.*,DEPT_NAME FROM EMPLOYEES_TAB E INNER JOIN DEPT D
WHERE E.DEPT_ID = D.DEPT_ID;

-- USING CO-RELATED SUB QUERY ( SLOWER THAN JOINS )

SELECT E.*,(SELECT DEPT_NAME FROM DEPT D WHERE D.DEPT_ID=E.DEPT_ID) DEPT_NAME FROM EMPLOYEES_TAB E;



-- 2) SHOW EMPLOYEES EARNING MORE THAN 40000

SELECT ENAME FROM EMPLOYEES_TAB
WHERE SALARY > 40000;



-- 3) COUNT EMPLOYEES PER DEPARTMENT

SELECT DEPT_ID,COUNT(*) EMPLOYEES_COUNT FROM EMPLOYEES_TAB
GROUP BY DEPT_ID;



-- 4) FIND AVERAGE SALARY PER DEPARTMENT 

SELECT DEPT_ID,AVG(SALARY) AVERAGE_SALARY FROM EMPLOYEES_TAB
GROUP BY DEPT_ID;



-- 5) FIND HIGHEST PAID EMPLOYEE IN EACH DEPARTMENT

SELECT ENAME,DEPT_ID,SALARY FROM EMPLOYEES_TAB E
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES_TAB WHERE DEPT_ID = E.DEPT_ID)
ORDER BY DEPT_ID ;



-- 6) EMPLOYEES WITH LOWER SALARY THAN DEPARTMENT AVERAGE

 /*  FOR UNDERSTANDING PURPOSE
 SELECT AVG(SALARY) FROM EMPLOYEES_TAB
GROUP BY DEPT_ID;

SELECT DEPT_ID,ENAME,SALARY FROM EMPLOYEES_TAB;
*/

SELECT ENAME,SALARY FROM EMPLOYEES_TAB E
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES_TAB WHERE E.DEPT_ID=DEPT_ID);



/*

--  CASE STATEMENT QUERIE --
 
 7) CATEGORIZE EMPLOYEES BASED ON SALARY ,
											-- HIGH >= 80000
											-- MEDIUM >= 70000
											-- LOW - OTHERWISE               
*/

SELECT E.*,
CASE WHEN SALARY >= 80000 THEN 'HIGH'
WHEN SALARY >= 70000 THEN 'MEDIUM'
ELSE 'LOW' 
END AS SALARY_POV FROM EMPLOYEES_TAB E;



/*
-- AGGREGATE FUNCTIONS + CASE STATEMENT --

 8) FIND THE DEPARTMENT MAXIMUM SALARY AND DISPLAY 'FINE' THEY ARE GETTING MAXIMUM SALARY IN THIER DEPARTMENT,
 ELSE DISPLAY 'TRY TO GET HIKE' .            

*/
 

SELECT ENAME , JOB , SALARY, MAX(SALARY) OVER (PARTITION BY JOB) DEPT_MAX_SAL,
CASE WHEN SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES_TAB E2 WHERE E1.JOB=E2.JOB ) THEN 'FINE' 
ELSE 'TRY TO GET HIKE' 
END AS SALARY_POV
FROM EMPLOYEES_TAB E1 
ORDER BY JOB ;



/*
-- SUB-QUERY --

9) DISPLAY EMPLOYEES EARNING MORE THAN DEPARTMENT AVERAGE        */

SELECT * FROM EMPLOYEES_TAB E 
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES_TAB J WHERE E.JOB=J.JOB);


/*


-- DATE FUNCTIONS--

10) FIND EMPLOYEES HAVING EXPERIENCE MORE THAN 2 YEARS    */

-- TO CALCULATE THIS... WE ASSUME TODAY'S DATE AND CALCULATE EMPLOYEES WHO HIRED BEFORE TODAY'S DATE 2 YEARS AGO
-- TODAY'S DATE 02-02-2026 

SELECT HIREDATE FROM EMPLOYEES_TAB;

SELECT HIREDATE FROM EMPLOYEES_TAB
WHERE HIREDATE < '2024-02-02';

-- END 
