-- CREATING DATABASE 

CREATE DATABASE EMP_MANAGEMENT_SYSTEM;

-- USE THAT DATABASE

USE EMP_MANAGEMENT_SYSTEM;

/*  DESIGN TABLES AND THIER STRUCTURES
HERE WE ARE GOING TO CREATE TWO TABLES (EMPLOYEE AND DEPARTMENT TABLE) AND DERIVE THIER STRUCTURES !!!
*/

CREATE TABLE EMPLOYEES_TAB (
EMP_ID INT PRIMARY KEY NOT NULL ,
ENAME VARCHAR(30),
DEPT_ID INT,
JOB VARCHAR(30),
SALARY INT,
HIREDATE DATE );

-- VIEW TABLE STRUCTURE

DESC EMPLOYEES_TAB;

-- CREATE DEPARTMENT TABLE

CREATE TABLE DEPT (
DEPT_ID INT PRIMARY KEY NOT NULL,
DEPT_NAME VARCHAR(30)
);

-- VIEW TABLE STRUCTURE

DESC DEPT;

-- ASSINGNING DEPT_ID AS A FORIEN KEY 

ALTER TABLE EMPLOYEES_TAB 
ADD CONSTRAINT FOREIGN KEY (DEPT_ID) REFERENCES DEPT(DEPT_ID) ;

-- THE TABLE CREATION PART IS FINISHED NOW WE'RE GOING TO ADD DATA'S INTO THAT TABLE

-- BEFORE THAT VIEW THAT TABLE 

SELECT * FROM EMPLOYEES_TAB;
